beaconapp/views/project.py
import os

from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for, jsonify
)
from werkzeug.exceptions import abort

from ..utils import capture_ip

from .. import repository

bp = Blueprint('project', __name__)

@bp.route('/')
@capture_ip
def index():
    projects = repository.get_projects()
    return render_template('project/index.html.j2',
        projects=projects)


def get_project_or_fail(project_id):
    project = repository.get_project(project_id)
    if project is None:
        abort(404, "Project ID {0} doesn't exist.".format(project_id))
    return project


@bp.route('/<int:project_id>', methods=('GET',))
@capture_ip
def browse_project(project_id):
    loc = repository.get_random_unverified_location(project_id)
    if loc is not None:
        return redirect(url_for('project.browse_location', project_id=project_id, location_id=loc[0]), code=303)
    return redirect(url_for('project.index'), code=303)
    #return render_template('project/item.html.j2', project=project)


@bp.route('/<int:project_id>/location/<int:location_id>', methods=('GET', 'POST'))
@capture_ip
def browse_location(project_id, location_id):
    if request.method == 'POST':
        try:    
            outcome = "FAIL"
            maybe = request.form.get('possible_location')
            if maybe is not None:
                outcome = "POSSIBLE"
            fail = request.form.get('not_location')
            if fail is not None:
                outcome = "FAIL"
            need_more = request.form['need_more_info']

            repository.insert_verification(location_id, g.remote_addr, outcome, need_more)
        except Exception as e:
            abort(400, str(e))

        loc = repository.get_random_unverified_location(project_id)
        if loc is not None:
            return redirect(url_for('project.browse_location', project_id=project_id, location_id=loc[0]), code=303)
        return redirect(url_for('project.index'), code=303)

    loc = repository.get_location(location_id)
    refs = repository.get_reference_images(project_id)
    photos = repository.get_street_images(location_id)
    return render_template('project/location.html.j2', reference_images=refs, street_images=photos, location=loc)

beaconapp/templates/base.html.j2
<!doctype html>
<head>
  <title>{% block title %}{% endblock %} - Beacon</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
  <nav>
    <h1>Beacon</h1>
  </nav>
  <section class="content">
    <header>
      {% block header %}{% endblock %}
    </header>
    {% for message in get_flashed_messages() %}
      <div class="flash">{{ message }}</div>
    {% endfor %}
    {% block content %}{% endblock %}
  </section>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  {% block scripts %}{% endblock %}
</body>

beaconapp/templates/project/index.html.j2
{% extends 'base.html.j2' %}

{% block header %}
  <h2>{% block title %}Projects{% endblock %}</h2>
{% endblock %}

{% block content %}
  {% for project in projects %}
    <article class="project">
      <header>
        <div>
          <h3><a href="{{ url_for('project.browse_project', project_id=project['id'])}}">{{ project['name'] }}</a></h3>
        </div>
      </header>
      <p class="body">{{ project['description'] or '' }}</p>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

beaconapp/templates/project/location.html.j2
{% extends 'base.html.j2' %}

{% block header %}
  <h4>{% block title %}Location {{ location['lat'] }}, {{ location['lon'] }}{% endblock %}</h4>
{% endblock %}

{% block content %}
<section class="reference-images">
    <div class="img-container">
    {% for img in reference_images %}
        <img src="/{{ img['IMAGE_PATH'] }}"/>
    {% endfor %}
    </div>
</section>
<br />
<section class="street-images">
    <div class="img-container">
    {% for img in street_images %}
        <a class="more_info" href="https://www.instantstreetview.com/@{{ location['lat'] }},{{ location['lon'] }},{{ img['heading'] }}h,5p,1z" target="_blank"><img src="/{{ img['IMAGE_PATH'] }}"/></a>
    {% endfor %}
    </div>
</section>
<section class="controls">
    <form method="POST" action="">
        <input id="need-more-info" type="hidden" name="need_more_info" value="0" />
        <input type="submit" name="possible_location" value="Possible Location 👍" />
        <input type="submit" name="not_location" value="Not the Location 👎" />
    </form>
</section>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
$('.more_info').click(function(e)
{
    $('#need-more-info').val(1)
});
</script>
{% endblock %}